### ISSUE TITLE
TypeError: <lambda>() missing 1 required positional argument: 'pid'

### ISSUE THREAD

**Issue by SamvitJ** [ergysr/DeepCC#20]
After installing imgaug and running `train_duke(opts);`, I encounter the following error:
```
[0m2018-09-07 06:41:59,343 [INFO] train: train_set: data/duke_train.csv[0m
Traceback (most recent call last):
  File "train.py", line 586, in <module>
    main()
  File "train.py", line 391, in main
    num_parallel_calls=args.loading_threads)
  File "/root/tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 988, in map
    return ParallelMapDataset(self, map_func, num_parallel_calls)
  File "/root/tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2230, in __init__
    super(ParallelMapDataset, self).__init__(input_dataset, map_func)
  File "/root/tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2198, in __init__
    map_func, "Dataset.map()", input_dataset)
  File "/root/tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1454, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "/root/tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/framework/function.py", line 481, in add_to_graph
    self._create_definition_if_needed()
  File "/root/tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/framework/function.py", line 337, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/root/tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/framework/function.py", line 346, in _create_definition_if_needed_impl
    self._capture_by_value, self._caller_device)
  File "/root/tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/framework/function.py", line 863, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "/root/tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1392, in tf_data_structured_function_wrapper
    ret = func(*nested_args)
TypeError: <lambda>() missing 1 required positional argument: 'pid'
```

What is this resolution of this issue?

**Comment by SamvitJ** [comment]
And if I pull in the latest changes to master, I get this error instead:
```
>> train_duke(opts);
Traceback (most recent call last):
  File "train.py", line 586, in <module>
    main()
  File "train.py", line 272, in main
    iaa.Crop(pc=(0, 0.125)),  # crop images from each side by 0 to 12.5% (randomly chosen)
TypeError: Crop() got an unexpected keyword argument 'pc'
```

**Comment by SamvitJ** [comment]
(Is the change from px to pc in this commit correct: https://github.com/ergysr/DeepCC/commit/0d41da0) ?

**Comment by SamvitJ** [comment]
If I revert that commit, I run into this issue:
```
>> train_duke(opts);
The directory experiments/demo_weighted_triplet already exists and is not empty.
```

This is odd because:
```
>> system('rm experiments/demo_weighted_triplet')
rm: cannot remove 'experiments/demo_weighted_triplet': No such file or directory
```

and adding --resume to train_duke.sh does not resolve the error.

**Comment by SamvitJ** [comment]
So to summarize, my original error on running `>> train_duke(opts);` was:
`TypeError: <lambda>() missing 1 required positional argument: 'pid'`

I then pulled in commits up to 819dae07 on master, and I hit this error:
`TypeError: Crop() got an unexpected keyword argument 'pc'`

Finally, reverting just commit 0d41da0 leads to this error:
`The directory experiments/demo_weighted_triplet already exists and is not empty. If you want to resume training, append --resume to your call.`

which is not resolved by adding the --resume flag to train_duke.sh:
```
diff --git a/src/triplet-reid/train_duke.sh b/src/triplet-reid/train_duke.sh
+       --resume \
```

**Comment by ergysr** [comment]
> TypeError: <lambda>() missing 1 required positional argument: 'pid'

Try with [this](https://github.com/ergysr/DeepCC/commit/cfa233a00a819d409b5c7927e5fdad7719aaa87c) change. If you still have issues see #12, or let me know.

> TypeError: Crop() got an unexpected keyword argument 'pc'.

The new change also fixes `pc` to `percent`.

> which is not resolved by adding the --resume flag to train_duke.sh:

You don't need to use the train_duke.sh script for the demo. Rather than resuming, I suggest that you delete the experiment folder which is created by default (`src/triplet-reid/experiments/demo_weighted_triplet`), then start training again.

**Comment by SamvitJ** [comment]
With those changes, it gets a little further, but then hits this error:
```
[0m2018-09-08 18:45:52,803 [INFO] tensorflow: Scale of 0 disables regularizer.[0m
[33m2018-09-08 18:45:54,999 [WARNING] tensorflow: From /ebs/DeepCC/src/triplet-reid/nets/resnet_v1.py:219: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead[0m
[33m2018-09-08 18:45:54,999 [WARNING] tensorflow: From /ebs/DeepCC/src/triplet-reid/nets/resnet_v1.py:219: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead[0m
2018-09-08 18:45:59.137527: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "train.py", line 586, in <module>
    main()
  File "train.py", line 517, in main
    saver.restore(sess, args.initial_checkpoint)
  File "/root/tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1717, in restore
    + compat.as_text(save_path))
ValueError: The passed save_path is not a valid checkpoint: resnet_v1_50.ckpt
```

**Comment by SamvitJ** [comment]
So reloading opts (`opts = get_opts();`) to use `experiment_root: 'src/triplet-reid/experiments'` resolves (hides?) this issue, but results in [#12](https://github.com/ergysr/DeepCC/issues/12).

**Comment by SamvitJ** [comment]
To follow up, if I switch to the absolute path `'/ebs/DeepCC/src/triplet-reid/experiments'` (for my directory structure) instead of just '/src/triplet-reid/experiments', I run into the previous, `save_path is not a valid checkpoint`, issue. Any help debugging this would be appreciated.

**Comment by ergysr** [comment]
The Python command for training should run from the triplet-reid folder level. In that folder you should also have the resnet_v1_50.ckpt file.

**Comment by SamvitJ** [comment]
Got it, thank you!

**Comment by ergysr** [comment]
Let me know if you still have issues. The code runs fine for me on a new linux machine with python3 and the latest changes.

**Comment by SamvitJ** [comment]
Do you have an estimate for how long training should take on a machine with e.g. 1 Tesla K80 GPU? It is currently showing an ETA of 10 days.
