### ISSUE TITLE
ValueError: Can't load save_path when it is None.

### ISSUE THREAD

**Issue by anilsh** [ergysr/DeepCC#38]
After running embed_detections(opts, detections) I am getting following error:

Restoring from checkpoint: None
Traceback (most recent call last):
File "embed_detections.py", line 247, in 
main()
File "embed_detections.py", line 208, in main
tf.train.Saver().restore(sess, checkpoint)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1534, in restore
raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

Any hacks to fix it?

**Comment by ergysr** [comment]
It seems that you are not providing a checkpoint with weights. Have you followed the steps for training an appearance model? This will generate a valid checkpoint.

**Comment by anilsh** [comment]
I have followed the steps mentioned in Training an appearance model section of the README. Do I need to do something else as well?

When I go through the code, checkpoint comes out to be None during restore. Do I need to download checkpoint from somewhere else? I guess this has to be provided manually because checkpoint is taken from command line arg (line 33 of embed.py).

**Comment by anilsh** [comment]
I have set that to `experiments/demo_weighted_triplet`. The same error is coming during training as well. `embed(opts)` is also generating same error.  I guess during training it should not ask for the pretrained model. Or I need to place resnet ckpt in this directory?

**Comment by anilsh** [comment]
Also, am I missing any step to retrain the appearance model? I am doing the following:

1. Placing resnet model in triplet_reid folder
2. imgaug was already installed
3. Images path is set to re-id images

**Comment by ergysr** [comment]
This looks correct. From which folder are you calling embed_detections?

**Comment by anilsh** [comment]
I am calling this from main folder of the project where demo.m is placed. 

Also do I need to download pretrained model from Beyer et al.'s re-id implementation?

**Comment by ergysr** [comment]
The resnet ckpt goes in the triplet reid folder but is not crucial. I wonder if you have tried separately to clone Beyer's repository and if that code trains and embeds. This would help narrow the source of the issue.

**Comment by anilsh** [comment]
`embed_detection(opts, detections)` is expected to give this error as there is no trained model in `experiments/demo_weighted_triplet`. But `embed(opts)` should not give this error because I can see that resume is set to false. Do I need to change any default parameter which is not mentioned in the README?

**Comment by anilsh** [comment]
Let me try that code.

**Comment by ergysr** [comment]
Also if experiments/demo_weighted_teiplet is empty then it I'm not sure the model has trained and produced any checkpoints.

**Comment by anilsh** [comment]
After training there are files in the folder namely duke_test_embeddings, duke_train_embeddings and train.log. All files are 800bytes but train.log has significant size. Clearly, training does not succeed and above error is prompted in matlab.

**Comment by ergysr** [comment]
So the issue is clearly with the training. You would have 25 checkpoint files after a successful training run, and the embeddings would be several MB.
